import setuptools

with open("readme.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="genomicinfo",
    version="0.0.1",
    author="Rishab Mallick",
    author_email="rishabmallick6@gmail.com",
    description="Extract genomic variants from scientific articles",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/rishabgit/genomic-info-from-papers",
    packages=setuptools.find_packages(),
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
    install_requires=[
        'accelerate==0.3.0',
        'argcomplete==2.0.0',
        'argh==0.26.2',
        'bcrypt==3.2.2',
        'beautifulsoup4==4.11.1',
        'bs4==0.0.1',
        'certifi==2021.10.8',
        'cffi==1.15.0',
        'chardet==4.0.0',
        'charset-normalizer==2.0.12',
        'click==8.1.3',
        'cryptography==37.0.2',
        'datasets==1.11.0',
        'dill==0.3.4',
        'fabric==2.5.0',
        'filelock==3.7.0',
        'fsspec==2022.3.0',
        'gensim==3.8.3',
        'gffutils==0.10.1',
        'huggingface-hub==0.0.12',
        'idna==3.3',
        'invoke==1.7.1',
        'joblib==1.1.0',
        'multiprocess==0.70.12.2',
        'nervaluate==0.1.8',
        'nltk==3.6.3',
        'numpy==1.19.5',
        'packaging==21.3',
        'pandas==1.3.5',
        'paramiko==2.10.4',
        'pdfminer.six==20201018',
        'psycopg2-binary==2.9.3',
        'pyaml==21.10.1',
        'pyarrow==8.0.0',
        'pybedtools==0.9.0',
        'pycparser==2.21',
        'pyfaidx==0.6.4',
        'PyNaCl==1.5.0',
        'pyparsing==3.0.9',
        'pysam==0.19.0',
        'python-dateutil==2.8.2',
        'pytz==2021.3',
        'PyYAML==6.0',
        'regex==2020.10.28',
        'requests==2.27.1',
        'sacremoses==0.0.53',
        'scikit-learn==1.1.0',
        'scipy==1.8.0',
        'seqeval==1.2.2',
        'simplejson==3.17.6',
        'six==1.16.0',
        'smart-open==6.0.0',
        'sortedcontainers==2.4.0',
        'soupsieve==2.3.2.post1',
        'threadpoolctl==3.1.0',
        'tokenizers==0.10.3',
        'torch==1.9.0',
        'tqdm==4.64.0',
        'transformers==4.9.1',
        'typing_extensions==4.2.0',
        'urllib3==1.26.9',
        'wbtools==1.3.0',
        'xxhash==3.0.0'
    ]
)
